redirect_console: True
wireless_namespace: 'ddwrt'
wpa_config: "/etc/ros/wifi/networks.conf" 
base_station: "basestation-novpn"
ping_port: 1194
tunnel_interface: 'tun9'
local_networks: [ '10.68.0.0/24', '10.69.0.0/24' ]

interfaces:
  wlan0: { type: wireless }
  wlan1: { type: wireless }
  wan0: { type: wired,  priority: 20 }
  lan3: { type: wired, priority: 10 }
  "basestation-local2@lan1": { type: static, name: bs@lan0, priority: 30 }
  "wifi-router@lan0": { type: static, name: bs@lan0 }
